const questions = [
  {
    stem: '学习的时候，窗外的事物或声音会引起你的注意力吗？',
    options: [{
      item: 'A',
      content: '经常',
      score: 0,
    }, {
      item: 'B',
      content: '偶尔',
      score: 1,
    }, {
      item: 'C',
      content: '从未',
      score: 2,
    }],
  }, {
    stem: '上课或写作业的时候，你会在书上或本子上画些图案吗？',
    options: [{
      item: 'A',
      content: '经常',
      score: 0,
    }, {
      item: 'B',
      content: '偶尔',
      score: 1,
    }, {
      item: 'C',
      content: '从未',
      score: 2,
    }],
  }, {
    stem: '你会经常看错题目吗，例如看错题号，填错选项，看错字等等？',
    options: [{
      item: 'A',
      content: '经常',
      score: 0,
    }, {
      item: 'B',
      content: '偶尔',
      score: 1,
    }, {
      item: 'C',
      content: '从未',
      score: 2,
    }],
  }, {
    stem: '你更符合下面哪种情况：',
    options: [{
      item: 'A',
      content: '看过的事物记忆深刻',
      score: 0,
    }, {
      item: 'B',
      content: '对声音敏感，听过就能记住',
      score: 1,
    }, {
      item: 'C',
      content: '用笔写过或者操作过才能记住',
      score: 2,
    }],
  }, {
    stem: '上课时你会更愿意做的是：',
    options: [{
      item: 'A',
      content: '目不转睛盯着老师和黑板',
      score: 0,
    }, {
      item: 'B',
      content: '不看人，只要听见声音就能吸收得很好',
      score: 1,
    }, {
      item: 'C',
      content: '交头接耳、比较好动',
      score: 2,
    }],
  }, {
    stem: '你更适合哪种理解类型：',
    options: [{
      item: 'A',
      content: '看到文字能理解',
      score: 0,
    }, {
      item: 'B',
      content: '听别人解说能理解',
      score: 1,
    }, {
      item: 'C',
      content: '需要别人演示能理解',
      score: 2,
    }],
  }, {
    stem: '你更符合哪种情况？',
    options: [{
      item: 'A',
      content: '看书很快，经常是泛读的',
      score: 0,
    }, {
      item: 'B',
      content: '不喜欢看书，喜欢听别人分享',
      score: 1,
    }, {
      item: 'C',
      content: '看书很慢，喜欢一边看一边记笔记',
      score: 2,
    }],
  }, {
    stem: '在业余时间，你最喜欢：',
    options: [{
      item: 'A',
      content: '看书或电视',
      score: 0,
    }, {
      item: 'B',
      content: '听音乐或交流 ',
      score: 1,
    }, {
      item: 'C',
      content: '做手工、运动、活动',
      score: 2,
    }],
  }, {
    stem: '当你感觉任务有点难度，你会怎么办？',
    options: [{
      item: 'A',
      content: '暂时不做等老师讲',
      score: 0,
    }, {
      item: 'B',
      content: '试着做1-2次，答不出来就算了',
      score: 1,
    }, {
      item: 'C',
      content: '多次尝试去解答出来',
      score: 2,
    }],
  }, {
    stem: '考试没考好你会：',
    options: [{
      item: 'A',
      content: '不想再学，学习太难了',
      score: 0,
    }, {
      item: 'B',
      content: '有时会放弃，大多数的时候，还是会继续学习',
      score: 1,
    }, {
      item: 'C',
      content: '查找原因，下次努力',
      score: 2,
    }],
  }, {
    stem: '你是否有过特别想要做一件事情，然后过两三天又不想去做了？',
    options: [{
      item: 'A',
      content: '经常',
      score: 0,
    }, {
      item: 'B',
      content: '偶尔',
      score: 1,
    }, {
      item: 'C',
      content: '从未',
      score: 2,
    }],
  }, {
    stem: '根据下面图形的规律，空缺的部分应该哪个图形呢？',
    options: [{
      item: 'A',
      content: 'yellow-grid',
      score: 1,
    }, {
      item: 'B',
      content: 'yellow-rhombus',
      score: 0,
    }, {
      item: 'C',
      content: 'green-gird',
      score: 0,
    }],
  }, {
    stem: '小明、小红、小张三个人在一起做作业，有一道数学题比较难，当他们三个人都把自己的解法说出来以后，小明说：“我做错了。”小红说：“小明做对了。”小张说：“我做错了。”在一旁的丽丽看到他们的答案并听了她们的意见后说：“你们三个人中有一个人做对了，有一个人说对了。”请问，他们三人中到底谁做对了？',
    options: [{
      item: 'A',
      content: '小明',
      score: 0,
    }, {
      item: 'B',
      content: '小红',
      score: 0,
    }, {
      item: 'C',
      content: '小张',
      score: 1,
    }],
  }, {
    stem: '一头牛，向北走10米，再向西走10米，再向南走10米，倒退右转，问牛的尾巴朝向哪儿？',
    options: [{
      item: 'A',
      content: '朝南',
      score: 0,
    }, {
      item: 'B',
      content: '朝北',
      score: 0,
    }, {
      item: 'C',
      content: '朝地',
      score: 1,
    }],
  }, {
    stem: '小华的爷爷有7个儿子，每个儿子又有一个妹妹，请问小华的爷爷有多少个孩子？',
    options: [{
      item: 'A',
      content: '7',
      score: 0,
    }, {
      item: 'B',
      content: '8',
      score: 1,
    }, {
      item: 'C',
      content: '14',
      score: 0,
    }],
  },
];

export default questions;
