export default {
  id: 361175,
  title: '<p>老师端多选题</p>',
  content: null,
  optionList: [
    '<p>多选题A<br/></p>',
    '<p>多选题B</p>',
    '<p>多选题C</p>',
    '<p>多选题D</p>',
  ],
  answerList: [
    'B',
  ],
  analysis: '<p>正确答案B哦</p>',
  subjectId: 1,
  gradeId: 1,
  phaseId: 1,
  termId: null,
  typeId: 2,
  questionType: '多选题',
  provinceId: null,
  cityId: null,
  countyId: null,
  schoolId: null,
  year: 2017,
  score: 3,
  sourceId: 2,
  difficulty: 2,
  distinction: 1,
  recommendationIndex: null,
  rating: 1,
  comprehensiveDegreeId: 2,
  abilityIdList: null,
  subjectCharacteristicIdList: null,
  editionIdList: null,
  chapterIdList: null,
  knowledgeIdList: [
    119118,
  ],
  examPointIdList: [],
  coreLiteracyIdList: null,
  costTime: null,
  browseCount: 0,
  quoteCount: 31,
  examCount: 0,
  correctRate: null,
  storageTime: null,
  sub: false,
  state: null,
  createdTime: 1536743864000,
  createdUser: 180,
  updatedTime: 1538126840000,
  updatedUser: 1325976815,
  versions: null,
  remarks: null,
  picUrl: null,
  cutUserId: null,
  auditCutUserId: null,
  entryUserId: null,
  auditEntryUserId: null,
  tagUserId1: null,
  tagUserId2: null,
  auditTagUserId: null,
  cutTime: null,
  auditCutTime: null,
  entryTime: null,
  auditEntryTime: null,
  tag1Time: null,
  tag2Time: null,
  auditTagTime: null,
  errType: 0,
  errReason: null,
  templateType: 2,
  adoptUser1Tag: null,
  adoptUser2Tag: null,
  children: null,
  questionTag1: null,
  questionTag2: null,
  tagAdopt: null,
  tagReason: null,
  tagFeedback1: null,
  tagFeedback2: null,
  auditTagFeedback: null,
  sceneIdList: null,
  suggestTime: 3,
  examTypeId: 2,
  tagUser1FeedbackAdoptFlag: null,
  tagUser2FeedbackAdoptFlag: null,
  auditTagUserFeedbackAdoptFlag: null,
  tagUser1AdoptFlag: null,
  tagUser2AdoptFlag: null,
  knowledgeNameList: [
    '二级知识点哈哈哈',
  ],
  examPointNameList: [],
  layoutStyle: 3,
  x1: null,
  y1: null,
  x2: null,
  y2: null,
  picIndex: null,
  label: '2017年全国Ⅰ卷',
  deleted: false,
  parentTypeId: 38,
  parentTypeName: '选择题',
  questionClassify: null,
  questionMatch: null,
  originPaperName: null,
  examPaperTypeId: 1,
}
